/*
 * Copyright (c) 2024 Angelo Cassano
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

import 'dart:collection';

import 'package:flavourist/src/exception/existing_flavor_dimensions_exception.dart';
import 'package:flavourist/src/exception/malformed_resource_exception.dart';
import 'package:flavourist/src/parser/models/config/android.dart';
import 'package:flavourist/src/parser/models/flavors/android/build_config_field.dart';
import 'package:flavourist/src/parser/models/flavors/android/res_value.dart';
import 'package:flavourist/src/processors/commons/string_processor.dart';

class AndroidBuildGradleProcessor extends StringProcessor {
  static const String androidEntryPoint = 'android {';
  static const String flavorDimensions = 'flavorDimensions';
  static const String beginFlavorDimensionsMarkup =
      '// ----- BEGIN flavorDimensions (autogenerated by flutter_flavorizr) -----';
  static const String endFlavorDimensionsMarkup =
      '// ----- END flavorDimensions (autogenerated by flutter_flavorizr) -----';
  static const String beginFlavorDisplayNamesMarkup =
      '// ----- BEGIN flavorDisplayNames (autogenerated by flavourist) -----';
  static const String endFlavorDisplayNamesMarkup =
      '// ----- END flavorDisplayNames (autogenerated by flavourist) -----';
  static const String beginVariantResourcesMarkup =
      '// ----- BEGIN flavouristVariantResources (autogenerated by flavourist) -----';
  static const String endVariantResourcesMarkup =
      '// ----- END flavouristVariantResources (autogenerated by flavourist) -----';

  AndroidBuildGradleProcessor({
    super.input,
    required super.config,
  });

  @override
  String execute() {
    final int androidPosition = input!.indexOf(androidEntryPoint);
    final bool existingFlavorDimensions = input!.contains(flavorDimensions);
    final int beginFlavorDimensionsMarkupPosition =
        input!.indexOf(beginFlavorDimensionsMarkup);
    final int endFlavorDimensionsMarkupPosition =
        input!.indexOf(endFlavorDimensionsMarkup);

    if (androidPosition < 0) {
      throw MalformedResourceException(input!);
    }

    if (existingFlavorDimensions &&
        (beginFlavorDimensionsMarkupPosition < 0 ||
            endFlavorDimensionsMarkupPosition < 0)) {
      throw ExistingFlavorDimensionsException(input!);
    }

    StringBuffer buffer = StringBuffer();

    // Inner blocks first; indices must be resolved on current [input] after each removal.
    _removeAutogeneratedBlock(
      beginVariantResourcesMarkup,
      endVariantResourcesMarkup,
    );
    _removeAutogeneratedBlock(
      beginFlavorDisplayNamesMarkup,
      endFlavorDisplayNamesMarkup,
    );
    _removeAutogeneratedBlock(
      beginFlavorDimensionsMarkup,
      endFlavorDimensionsMarkup,
    );
    _appendStartContent(buffer, androidPosition);
    _appendFlavorsDimension(buffer);
    _appendFlavors(buffer);
    _appendFlavorDisplayNames(buffer);
    if (_hasVariantIcons) {
      _appendVariantResources(buffer);
    }

    _appendEndContent(buffer, androidPosition);

    return buffer.toString();
  }

  /// Removes a flavourist autogenerated block (markers inclusive).
  ///
  /// [endMarkup] is searched only after [beginMarkup] on the current [input].
  void _removeAutogeneratedBlock(String beginMarkup, String endMarkup) {
    final String content = input!;
    final int beginPos = content.indexOf(beginMarkup);
    if (beginPos < 0) {
      return;
    }

    final int endPos = content.indexOf(endMarkup, beginPos);
    if (endPos < 0) {
      return;
    }

    var removeStart = beginPos;
    if (removeStart >= 1 && content[removeStart - 1] == '\n') {
      removeStart--;
    }
    if (removeStart >= 1 && content[removeStart - 1] == '\n') {
      removeStart--;
    }

    var removeEnd = endPos + endMarkup.length;
    if (removeEnd < content.length && content[removeEnd] == '\r') {
      removeEnd++;
    }
    if (removeEnd < content.length && content[removeEnd] == '\n') {
      removeEnd++;
    }
    if (removeEnd < content.length && content[removeEnd] == '\n') {
      removeEnd++;
    }

    input = content.replaceRange(removeStart, removeEnd, '');
  }

  bool get _hasVariantIcons => config.flavors.values.any(
        (flavor) =>
            flavor.betaIcon != null ||
            flavor.debugIcon != null ||
            flavor.profileIcon != null,
      );

  void _appendStartContent(StringBuffer buffer, int androidPosition) {
    buffer.writeln(
        input!.substring(0, androidPosition + androidEntryPoint.length));
  }

  void _appendFlavorsDimension(StringBuffer buffer) {
    final flavorDimension =
        config.app?.android?.flavorDimensions ?? Android.kFlavorDimensionValue;

    buffer.writeln();
    buffer.writeln('    $beginFlavorDimensionsMarkup');
    buffer.writeln('    flavorDimensions += "$flavorDimension"');
    buffer.writeln();
  }

  void _appendFlavors(StringBuffer buffer) {
    final flavorDimension =
        config.app?.android?.flavorDimensions ?? Android.kFlavorDimensionValue;

    buffer.writeln('    productFlavors {');

    config.androidFlavors.forEach((name, flavor) {
      buffer.writeln('        $name {');
      buffer.writeln('            dimension "$flavorDimension"');
      buffer.writeln(
          '            applicationId "${flavor.android?.applicationID ?? flavor.applicationID}"');

      flavor.android?.customConfig.forEach((key, value) {
        buffer.writeln('            $key $value');
      });

      final Map<String, ResValue> resValues = LinkedHashMap.from(
        config.app?.android?.resValues ?? {},
      )..addAll(flavor.android?.resValues ?? {});
      resValues.forEach((key, res) {
        buffer.writeln(
            '            resValue "${res.type}", "$key", "${res.value}"');
      });

      final Map<String, BuildConfigField> buildConfigFields =
          LinkedHashMap.fromEntries([
        ...config.app?.android?.buildConfigFields.entries ?? [],
        ...flavor.android?.buildConfigFields.entries ?? []
      ]);
      buildConfigFields.forEach((key, res) {
        buffer.writeln(
            '            buildConfigField "${res.type}", "$key", ${res.wrappedValue}');
      });

      buffer.writeln('        }');
    });

    buffer.writeln('    }');
    buffer.writeln();
  }

  void _appendFlavorDisplayNames(StringBuffer buffer) {
    buffer.writeln('    $beginFlavorDisplayNamesMarkup');
    _writeDartBuildTypeParserFunction(buffer);
    _writeDartBuildTypeParser(buffer);
    buffer.writeln('    applicationVariants.configureEach { variant ->');
    buffer.writeln('        def displayNames = [');

    config.androidFlavors.forEach((name, flavor) {
      final escaped = _escapeGroovyString(flavor.name);
      buffer.writeln('            $name: "$escaped",');
    });

    buffer.writeln('        ]');
    buffer.writeln('        def baseName = displayNames[variant.flavorName]');
    buffer.writeln('        if (baseName == null) {');
    buffer.writeln('            return');
    buffer.writeln('        }');
    buffer.writeln('        def effectiveBuildType = variant.buildType.name');
    buffer.writeln(
        '        if (effectiveBuildType == "release" && flavouristDartBuildType != null) {',
    );
    buffer.writeln('            effectiveBuildType = flavouristDartBuildType');
    buffer.writeln('        }');
    buffer.writeln('        def label = baseName');
    buffer.writeln('        switch (effectiveBuildType) {');
    buffer.writeln('            case "debug":');
    buffer.writeln('                label = baseName + " (Debug)"');
    buffer.writeln('                break');
    buffer.writeln('            case "profile":');
    buffer.writeln('                label = baseName + " (Profile)"');
    buffer.writeln('                break');
    buffer.writeln('            case "beta":');
    buffer.writeln('                label = baseName + " (Beta)"');
    buffer.writeln('                break');
    buffer.writeln('        }');
    buffer.writeln('        variant.resValue "string", "app_name", label');
    buffer.writeln('    }');
    buffer.writeln();
    buffer.writeln('    $endFlavorDisplayNamesMarkup');
    buffer.writeln();
  }

  /// When Flutter runs ``--release`` with ``BUILD_TYPE=beta`` (or debug/profile),
  /// Gradle still uses the release build type. Merge ``src/{flavor}{Variant}/res``
  /// so per-variant launcher icons from [flavors.yaml] apply.
  void _appendVariantResources(StringBuffer buffer) {
    buffer.writeln('    $beginVariantResourcesMarkup');
    buffer.writeln('    afterEvaluate {');
    buffer.writeln('        def dartBuildType = flavouristParseDartBuildType()');
    buffer.writeln('        android.applicationVariants.configureEach { variant ->');
    buffer.writeln('            def nativeBuildType = variant.buildType.name');
    buffer.writeln('            def effectiveIconVariant = nativeBuildType');
    buffer.writeln(
        '            if (nativeBuildType == "release" && dartBuildType != null && dartBuildType != "release") {',
    );
    buffer.writeln('                effectiveIconVariant = dartBuildType');
    buffer.writeln('            }');
    buffer.writeln(
        '            if (effectiveIconVariant == nativeBuildType) {',
    );
    buffer.writeln('                return');
    buffer.writeln('            }');
    buffer.writeln(
        '            if (effectiveIconVariant != "debug" && effectiveIconVariant != "beta" && effectiveIconVariant != "profile") {',
    );
    buffer.writeln('                return');
    buffer.writeln('            }');
    buffer.writeln(
        '            def overlaySuffix = effectiveIconVariant.substring(0, 1).toUpperCase() + effectiveIconVariant.substring(1)',
    );
    buffer.writeln(
        '            def overlayDir = file("src/\${variant.flavorName}\${overlaySuffix}/res")',
    );
    buffer.writeln('            if (!overlayDir.exists()) {');
    buffer.writeln('                return');
    buffer.writeln('            }');
    buffer.writeln(
        '            def variantSourceSet = android.sourceSets.findByName(variant.name)',
    );
    buffer.writeln('            if (variantSourceSet != null) {');
    buffer.writeln('                variantSourceSet.res.srcDirs(overlayDir)');
    buffer.writeln('            }');
    buffer.writeln('        }');
    buffer.writeln('    }');
    buffer.writeln();
    buffer.writeln('    $endVariantResourcesMarkup');
    buffer.writeln();
  }

  void _writeDartBuildTypeParser(StringBuffer buffer) {
    buffer.writeln('    def flavouristDartBuildType = flavouristParseDartBuildType()');
    buffer.writeln();
  }

  void _writeDartBuildTypeParserFunction(StringBuffer buffer) {
    buffer.writeln('    def flavouristParseDartBuildType = {');
    buffer.writeln('        if (!project.hasProperty("dart-defines")) {');
    buffer.writeln('            return null');
    buffer.writeln('        }');
    buffer.writeln(
        '        for (encoded in project.property("dart-defines").toString().split(",")) {',
    );
    buffer.writeln('            if (encoded.isEmpty()) {');
    buffer.writeln('                continue');
    buffer.writeln('            }');
    buffer.writeln('            try {');
    buffer.writeln(
        '                def decoded = new String(java.util.Base64.decoder.decode(encoded.trim()), java.nio.charset.StandardCharsets.UTF_8)',
    );
    buffer.writeln('                if (decoded.startsWith("BUILD_TYPE=")) {');
    buffer.writeln(
        '                    return decoded.substring("BUILD_TYPE=".length())',
    );
    buffer.writeln('                }');
    buffer.writeln('            } catch (Exception ignored) {');
    buffer.writeln('            }');
    buffer.writeln('        }');
    buffer.writeln('        return null');
    buffer.writeln('    }');
    buffer.writeln();
  }

  String _escapeGroovyString(String value) =>
      value.replaceAll(r'\', r'\\').replaceAll('"', r'\"');

  void _appendEndContent(StringBuffer buffer, int androidPosition) {
    buffer.writeln('    $endFlavorDimensionsMarkup');
    buffer.write(
        input!.substring(androidPosition + androidEntryPoint.length + 1));
  }

  @override
  String toString() => 'AndroidBuildGradleProcessor';
}
